//-----------------------------------------------------------------------
// <copyright file="ReportingServices2010MetadataProvider.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
//----------------------------------------------------------------

namespace ReportingServicesSchema_2010.Schema
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.235
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling", IsNullable = false)]
    public partial class SemanticModel
    {

        private string descriptionField;

        private string versionField;

        private string cultureField;

        private object[] entitiesField;

        private PerspectiveType[] perspectivesField;

        private CustomPropertyType[] customPropertiesField;

        private System.Xml.XmlQualifiedName idField;

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "language")]
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entity", typeof(EntityType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EntityFolder", typeof(EntityFolderType), IsNullable = false)]
        public object[] Entities
        {
            get
            {
                return this.entitiesField;
            }
            set
            {
                this.entitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Perspective", IsNullable = false)]
        public PerspectiveType[] Perspectives
        {
            get
            {
                return this.perspectivesField;
            }
            set
            {
                this.perspectivesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class EntityType
    {

        private string nameField;

        private string descriptionField;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        private CustomPropertyType[] customPropertiesField;

        private string collectionNameField;

        private AttributeReferenceType[] identifyingAttributesField;

        private AttributeReferenceType[] defaultDetailAttributesField;

        private AttributeReferenceType[] defaultAggregateAttributesField;

        private SortAttributeType[] sortAttributesField;

        private EntityTypeInstanceSelection instanceSelectionField;

        private bool isLookupField;

        private bool isLookupFieldSpecified;

        private EntityTypeInheritance inheritanceField;

        private bool disjointInheritanceField;

        private bool disjointInheritanceFieldSpecified;

        private object[] fieldsField;

        private AttributeReferenceType[] securityFiltersField;

        private DefaultSecurityFilterType defaultSecurityFilterField;

        private TableType tableField;

        private ColumnType columnField;

        private System.Xml.XmlQualifiedName idField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        public string CollectionName
        {
            get
            {
                return this.collectionNameField;
            }
            set
            {
                this.collectionNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttributeReference", IsNullable = false)]
        public AttributeReferenceType[] IdentifyingAttributes
        {
            get
            {
                return this.identifyingAttributesField;
            }
            set
            {
                this.identifyingAttributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttributeReference", IsNullable = false)]
        public AttributeReferenceType[] DefaultDetailAttributes
        {
            get
            {
                return this.defaultDetailAttributesField;
            }
            set
            {
                this.defaultDetailAttributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttributeReference", IsNullable = false)]
        public AttributeReferenceType[] DefaultAggregateAttributes
        {
            get
            {
                return this.defaultAggregateAttributesField;
            }
            set
            {
                this.defaultAggregateAttributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SortAttribute", IsNullable = false)]
        public SortAttributeType[] SortAttributes
        {
            get
            {
                return this.sortAttributesField;
            }
            set
            {
                this.sortAttributesField = value;
            }
        }

        /// <remarks/>
        public EntityTypeInstanceSelection InstanceSelection
        {
            get
            {
                return this.instanceSelectionField;
            }
            set
            {
                this.instanceSelectionField = value;
            }
        }

        /// <remarks/>
        public bool IsLookup
        {
            get
            {
                return this.isLookupField;
            }
            set
            {
                this.isLookupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsLookupSpecified
        {
            get
            {
                return this.isLookupFieldSpecified;
            }
            set
            {
                this.isLookupFieldSpecified = value;
            }
        }

        /// <remarks/>
        public EntityTypeInheritance Inheritance
        {
            get
            {
                return this.inheritanceField;
            }
            set
            {
                this.inheritanceField = value;
            }
        }

        /// <remarks/>
        public bool DisjointInheritance
        {
            get
            {
                return this.disjointInheritanceField;
            }
            set
            {
                this.disjointInheritanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisjointInheritanceSpecified
        {
            get
            {
                return this.disjointInheritanceFieldSpecified;
            }
            set
            {
                this.disjointInheritanceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", typeof(AttributeType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldFolder", typeof(FieldFolderType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Role", typeof(RoleType), IsNullable = false)]
        public object[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttributeReference", IsNullable = false)]
        public AttributeReferenceType[] SecurityFilters
        {
            get
            {
                return this.securityFiltersField;
            }
            set
            {
                this.securityFiltersField = value;
            }
        }

        /// <remarks/>
        public DefaultSecurityFilterType DefaultSecurityFilter
        {
            get
            {
                return this.defaultSecurityFilterField;
            }
            set
            {
                this.defaultSecurityFilterField = value;
            }
        }

        /// <remarks/>
        public TableType Table
        {
            get
            {
                return this.tableField;
            }
            set
            {
                this.tableField = value;
            }
        }

        /// <remarks/>
        public ColumnType Column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    //public partial class CustomPropertyType
    //{

    //    private string valueField;

    //    private System.Xml.XmlQualifiedName nameField;

    //    /// <remarks/>
    //    public string Value
    //    {
    //        get
    //        {
    //            return this.valueField;
    //        }
    //        set
    //        {
    //            this.valueField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public System.Xml.XmlQualifiedName Name
    //    {
    //        get
    //        {
    //            return this.nameField;
    //        }
    //        set
    //        {
    //            this.nameField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class ParameterType
    {

        private LiteralDataTypeEnum dataTypeField;

        private bool nullableField;

        private bool nullableFieldSpecified;

        private ParameterTypeCardinality cardinalityField;

        private bool cardinalityFieldSpecified;

        private ExpressionType expressionField;

        private string nameField;

        /// <remarks/>
        public LiteralDataTypeEnum DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }

        /// <remarks/>
        public bool Nullable
        {
            get
            {
                return this.nullableField;
            }
            set
            {
                this.nullableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NullableSpecified
        {
            get
            {
                return this.nullableFieldSpecified;
            }
            set
            {
                this.nullableFieldSpecified = value;
            }
        }

        /// <remarks/>
        public ParameterTypeCardinality Cardinality
        {
            get
            {
                return this.cardinalityField;
            }
            set
            {
                this.cardinalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CardinalitySpecified
        {
            get
            {
                return this.cardinalityFieldSpecified;
            }
            set
            {
                this.cardinalityFieldSpecified = value;
            }
        }

        /// <remarks/>
        public ExpressionType Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum LiteralDataTypeEnum
    {

        /// <remarks/>
        String,

        /// <remarks/>
        Integer,

        /// <remarks/>
        Decimal,

        /// <remarks/>
        Float,

        /// <remarks/>
        Boolean,

        /// <remarks/>
        DateTime,

        /// <remarks/>
        Time,

        /// <remarks/>
        EntityKey,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum ParameterTypeCardinality
    {

        /// <remarks/>
        One,

        /// <remarks/>
        Many,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class ExpressionType
    {

        private RolePathItemType[] pathField;

        private FunctionType functionField;

        private AttributeRefType attributeRefField;

        private EntityRefType entityRefField;

        private ParameterRefType parameterRefField;

        private LiteralType literalField;

        private NullType nullField;

        private CustomPropertyType[] customPropertiesField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RolePathItem", IsNullable = false)]
        public RolePathItemType[] Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public FunctionType Function
        {
            get
            {
                return this.functionField;
            }
            set
            {
                this.functionField = value;
            }
        }

        /// <remarks/>
        public AttributeRefType AttributeRef
        {
            get
            {
                return this.attributeRefField;
            }
            set
            {
                this.attributeRefField = value;
            }
        }

        /// <remarks/>
        public EntityRefType EntityRef
        {
            get
            {
                return this.entityRefField;
            }
            set
            {
                this.entityRefField = value;
            }
        }

        /// <remarks/>
        public ParameterRefType ParameterRef
        {
            get
            {
                return this.parameterRefField;
            }
            set
            {
                this.parameterRefField = value;
            }
        }

        /// <remarks/>
        public LiteralType Literal
        {
            get
            {
                return this.literalField;
            }
            set
            {
                this.literalField = value;
            }
        }

        /// <remarks/>
        public NullType Null
        {
            get
            {
                return this.nullField;
            }
            set
            {
                this.nullField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class RolePathItemType
    {

        private System.Xml.XmlQualifiedName roleIDField;

        /// <remarks/>
        public System.Xml.XmlQualifiedName RoleID
        {
            get
            {
                return this.roleIDField;
            }
            set
            {
                this.roleIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class FunctionType
    {

        private string functionNameField;

        private ExpressionType[] argumentsField;

        /// <remarks/>
        public string FunctionName
        {
            get
            {
                return this.functionNameField;
            }
            set
            {
                this.functionNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Expression", IsNullable = false)]
        public ExpressionType[] Arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class AttributeRefType
    {

        private System.Xml.XmlQualifiedName attributeIDField;

        private string attributeNameField;

        /// <remarks/>
        public System.Xml.XmlQualifiedName AttributeID
        {
            get
            {
                return this.attributeIDField;
            }
            set
            {
                this.attributeIDField = value;
            }
        }

        /// <remarks/>
        public string AttributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class EntityRefType
    {

        private System.Xml.XmlQualifiedName entityIDField;

        /// <remarks/>
        public System.Xml.XmlQualifiedName EntityID
        {
            get
            {
                return this.entityIDField;
            }
            set
            {
                this.entityIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class ParameterRefType
    {

        private string parameterNameField;

        /// <remarks/>
        public string ParameterName
        {
            get
            {
                return this.parameterNameField;
            }
            set
            {
                this.parameterNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class LiteralType
    {

        private LiteralDataTypeEnum dataTypeField;

        private string valueField;

        private string[] valuesField;

        /// <remarks/>
        public LiteralDataTypeEnum DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable = false)]
        public string[] Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class NullType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class SubtotalSetType
    {

        private string[] subtotalGroupingsField;

        private string[] subtotalMeasuresField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("GroupingName", IsNullable = false)]
        public string[] SubtotalGroupings
        {
            get
            {
                return this.subtotalGroupingsField;
            }
            set
            {
                this.subtotalGroupingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MeasureName", IsNullable = false)]
        public string[] SubtotalMeasures
        {
            get
            {
                return this.subtotalMeasuresField;
            }
            set
            {
                this.subtotalMeasuresField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class MeasureGroupType
    {

        private BaseEntityType baseEntityField;

        private ExpressionType[] measuresField;

        private SubtotalSetType[] subtotalSetsField;

        /// <remarks/>
        public BaseEntityType BaseEntity
        {
            get
            {
                return this.baseEntityField;
            }
            set
            {
                this.baseEntityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Expression", IsNullable = false)]
        public ExpressionType[] Measures
        {
            get
            {
                return this.measuresField;
            }
            set
            {
                this.measuresField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SubtotalSet", IsNullable = false)]
        public SubtotalSetType[] SubtotalSets
        {
            get
            {
                return this.subtotalSetsField;
            }
            set
            {
                this.subtotalSetsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class BaseEntityType
    {

        private System.Xml.XmlQualifiedName entityIDField;

        /// <remarks/>
        public System.Xml.XmlQualifiedName EntityID
        {
            get
            {
                return this.entityIDField;
            }
            set
            {
                this.entityIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class GroupingType
    {

        private ExpressionType expressionField;

        private ExpressionType[] detailsField;

        private string nameField;

        /// <remarks/>
        public ExpressionType Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Expression", IsNullable = false)]
        public ExpressionType[] Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class HierarchyType
    {

        private BaseEntityType baseEntityField;

        private GroupingType[] groupingsField;

        private HierarchyTypeFilter filterField;

        /// <remarks/>
        public BaseEntityType BaseEntity
        {
            get
            {
                return this.baseEntityField;
            }
            set
            {
                this.baseEntityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Grouping", IsNullable = false)]
        public GroupingType[] Groupings
        {
            get
            {
                return this.groupingsField;
            }
            set
            {
                this.groupingsField = value;
            }
        }

        /// <remarks/>
        public HierarchyTypeFilter Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class HierarchyTypeFilter
    {

        private ExpressionType expressionField;

        /// <remarks/>
        public ExpressionType Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class PerspectiveType
    {

        private string nameField;

        private string descriptionField;

        private System.Xml.XmlQualifiedName[] modelItemsField;

        private CustomPropertyType[] customPropertiesField;

        private System.Xml.XmlQualifiedName idField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ModelItemID", IsNullable = false)]
        public System.Xml.XmlQualifiedName[] ModelItems
        {
            get
            {
                return this.modelItemsField;
            }
            set
            {
                this.modelItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class EntityFolderType
    {

        private string nameField;

        private string descriptionField;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        private CustomPropertyType[] customPropertiesField;

        private object[] entitiesField;

        private System.Xml.XmlQualifiedName idField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entity", typeof(EntityType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EntityFolder", typeof(EntityFolderType), IsNullable = false)]
        public object[] Entities
        {
            get
            {
                return this.entitiesField;
            }
            set
            {
                this.entitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class TableType
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class DefaultSecurityFilterType
    {

        private AttributeReferenceType attributeReferenceField;

        /// <remarks/>
        public AttributeReferenceType AttributeReference
        {
            get
            {
                return this.attributeReferenceField;
            }
            set
            {
                this.attributeReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class AttributeReferenceType
    {

        private RolePathItemType[] pathField;

        private System.Xml.XmlQualifiedName attributeIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RolePathItem", IsNullable = false)]
        public RolePathItemType[] Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlQualifiedName AttributeID
        {
            get
            {
                return this.attributeIDField;
            }
            set
            {
                this.attributeIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class FieldFolderType
    {

        private string nameField;

        private string descriptionField;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        private CustomPropertyType[] customPropertiesField;

        private object[] fieldsField;

        private System.Xml.XmlQualifiedName idField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", typeof(AttributeType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldFolder", typeof(FieldFolderType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Role", typeof(RoleType), IsNullable = false)]
        public object[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class AttributeType
    {

        private string nameField;

        private string descriptionField;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        private CustomPropertyType[] customPropertiesField;

        private object[] variationsField;

        private DataTypeEnum dataTypeField;

        private bool nullableField;

        private bool nullableFieldSpecified;

        private ExpressionType expressionField;

        private bool isAggregateField;

        private bool isAggregateFieldSpecified;

        private bool isFilterField;

        private bool isFilterFieldSpecified;

        private bool omitSecurityFiltersField;

        private bool omitSecurityFiltersFieldSpecified;

        private SortDirectionEnum sortDirectionField;

        private bool sortDirectionFieldSpecified;

        private int widthField;

        private bool widthFieldSpecified;

        private AttributeTypeAlignment alignmentField;

        private bool alignmentFieldSpecified;

        private string formatField;

        private string mimeTypeField;

        private string dataCultureField;

        private bool discourageGroupingField;

        private bool discourageGroupingFieldSpecified;

        private bool enableDrillthroughField;

        private bool enableDrillthroughFieldSpecified;

        private AttributeContextualNameEnum contextualNameField;

        private bool contextualNameFieldSpecified;

        private System.Xml.XmlQualifiedName defaultAggregateAttributeIDField;

        private AttributeTypeValueSelection valueSelectionField;

        private bool valueSelectionFieldSpecified;

        private ColumnType columnField;

        private System.Xml.XmlQualifiedName idField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", typeof(AttributeType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Role", typeof(RoleType), IsNullable = false)]
        public object[] Variations
        {
            get
            {
                return this.variationsField;
            }
            set
            {
                this.variationsField = value;
            }
        }

        /// <remarks/>
        public DataTypeEnum DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }

        /// <remarks/>
        public bool Nullable
        {
            get
            {
                return this.nullableField;
            }
            set
            {
                this.nullableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NullableSpecified
        {
            get
            {
                return this.nullableFieldSpecified;
            }
            set
            {
                this.nullableFieldSpecified = value;
            }
        }

        /// <remarks/>
        public ExpressionType Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }

        /// <remarks/>
        public bool IsAggregate
        {
            get
            {
                return this.isAggregateField;
            }
            set
            {
                this.isAggregateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsAggregateSpecified
        {
            get
            {
                return this.isAggregateFieldSpecified;
            }
            set
            {
                this.isAggregateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool IsFilter
        {
            get
            {
                return this.isFilterField;
            }
            set
            {
                this.isFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsFilterSpecified
        {
            get
            {
                return this.isFilterFieldSpecified;
            }
            set
            {
                this.isFilterFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool OmitSecurityFilters
        {
            get
            {
                return this.omitSecurityFiltersField;
            }
            set
            {
                this.omitSecurityFiltersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OmitSecurityFiltersSpecified
        {
            get
            {
                return this.omitSecurityFiltersFieldSpecified;
            }
            set
            {
                this.omitSecurityFiltersFieldSpecified = value;
            }
        }

        /// <remarks/>
        public SortDirectionEnum SortDirection
        {
            get
            {
                return this.sortDirectionField;
            }
            set
            {
                this.sortDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortDirectionSpecified
        {
            get
            {
                return this.sortDirectionFieldSpecified;
            }
            set
            {
                this.sortDirectionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified
        {
            get
            {
                return this.widthFieldSpecified;
            }
            set
            {
                this.widthFieldSpecified = value;
            }
        }

        /// <remarks/>
        public AttributeTypeAlignment Alignment
        {
            get
            {
                return this.alignmentField;
            }
            set
            {
                this.alignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlignmentSpecified
        {
            get
            {
                return this.alignmentFieldSpecified;
            }
            set
            {
                this.alignmentFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "language")]
        public string DataCulture
        {
            get
            {
                return this.dataCultureField;
            }
            set
            {
                this.dataCultureField = value;
            }
        }

        /// <remarks/>
        public bool DiscourageGrouping
        {
            get
            {
                return this.discourageGroupingField;
            }
            set
            {
                this.discourageGroupingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscourageGroupingSpecified
        {
            get
            {
                return this.discourageGroupingFieldSpecified;
            }
            set
            {
                this.discourageGroupingFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool EnableDrillthrough
        {
            get
            {
                return this.enableDrillthroughField;
            }
            set
            {
                this.enableDrillthroughField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableDrillthroughSpecified
        {
            get
            {
                return this.enableDrillthroughFieldSpecified;
            }
            set
            {
                this.enableDrillthroughFieldSpecified = value;
            }
        }

        /// <remarks/>
        public AttributeContextualNameEnum ContextualName
        {
            get
            {
                return this.contextualNameField;
            }
            set
            {
                this.contextualNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContextualNameSpecified
        {
            get
            {
                return this.contextualNameFieldSpecified;
            }
            set
            {
                this.contextualNameFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlQualifiedName DefaultAggregateAttributeID
        {
            get
            {
                return this.defaultAggregateAttributeIDField;
            }
            set
            {
                this.defaultAggregateAttributeIDField = value;
            }
        }

        /// <remarks/>
        public AttributeTypeValueSelection ValueSelection
        {
            get
            {
                return this.valueSelectionField;
            }
            set
            {
                this.valueSelectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSelectionSpecified
        {
            get
            {
                return this.valueSelectionFieldSpecified;
            }
            set
            {
                this.valueSelectionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public ColumnType Column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class RoleType
    {

        private string nameField;

        private string descriptionField;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        private CustomPropertyType[] customPropertiesField;

        private object[] variationsField;

        private LinguisticsType linguisticsField;

        private System.Xml.XmlQualifiedName relatedRoleIDField;

        private RoleTypeCardinality cardinalityField;

        private RoleTypeContextualName contextualNameField;

        private bool contextualNameFieldSpecified;

        private System.Xml.XmlQualifiedName[] hiddenFieldsField;

        private bool preferredField;

        private bool preferredFieldSpecified;

        private bool promoteLookupField;

        private bool promoteLookupFieldSpecified;

        private bool expandInlineField;

        private bool expandInlineFieldSpecified;

        private RelationType relationField;

        private System.Xml.XmlQualifiedName idField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", typeof(AttributeType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Role", typeof(RoleType), IsNullable = false)]
        public object[] Variations
        {
            get
            {
                return this.variationsField;
            }
            set
            {
                this.variationsField = value;
            }
        }

        /// <remarks/>
        public LinguisticsType Linguistics
        {
            get
            {
                return this.linguisticsField;
            }
            set
            {
                this.linguisticsField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlQualifiedName RelatedRoleID
        {
            get
            {
                return this.relatedRoleIDField;
            }
            set
            {
                this.relatedRoleIDField = value;
            }
        }

        /// <remarks/>
        public RoleTypeCardinality Cardinality
        {
            get
            {
                return this.cardinalityField;
            }
            set
            {
                this.cardinalityField = value;
            }
        }

        /// <remarks/>
        public RoleTypeContextualName ContextualName
        {
            get
            {
                return this.contextualNameField;
            }
            set
            {
                this.contextualNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContextualNameSpecified
        {
            get
            {
                return this.contextualNameFieldSpecified;
            }
            set
            {
                this.contextualNameFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldFolderItemID", IsNullable = false)]
        public System.Xml.XmlQualifiedName[] HiddenFields
        {
            get
            {
                return this.hiddenFieldsField;
            }
            set
            {
                this.hiddenFieldsField = value;
            }
        }

        /// <remarks/>
        public bool Preferred
        {
            get
            {
                return this.preferredField;
            }
            set
            {
                this.preferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredSpecified
        {
            get
            {
                return this.preferredFieldSpecified;
            }
            set
            {
                this.preferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool PromoteLookup
        {
            get
            {
                return this.promoteLookupField;
            }
            set
            {
                this.promoteLookupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PromoteLookupSpecified
        {
            get
            {
                return this.promoteLookupFieldSpecified;
            }
            set
            {
                this.promoteLookupFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool ExpandInline
        {
            get
            {
                return this.expandInlineField;
            }
            set
            {
                this.expandInlineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpandInlineSpecified
        {
            get
            {
                return this.expandInlineFieldSpecified;
            }
            set
            {
                this.expandInlineFieldSpecified = value;
            }
        }

        /// <remarks/>
        public RelationType Relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class LinguisticsType
    {

        private string singularNameField;

        private string pluralNameField;

        /// <remarks/>
        public string SingularName
        {
            get
            {
                return this.singularNameField;
            }
            set
            {
                this.singularNameField = value;
            }
        }

        /// <remarks/>
        public string PluralName
        {
            get
            {
                return this.pluralNameField;
            }
            set
            {
                this.pluralNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum RoleTypeCardinality
    {

        /// <remarks/>
        One,

        /// <remarks/>
        Many,

        /// <remarks/>
        OptionalOne,

        /// <remarks/>
        OptionalMany,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum RoleTypeContextualName
    {

        /// <remarks/>
        Default,

        /// <remarks/>
        Role,

        /// <remarks/>
        Merge,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class RelationType
    {

        private string nameField;

        private RelationTypeRelationEnd relationEndField;

        private bool relationEndFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RelationTypeRelationEnd RelationEnd
        {
            get
            {
                return this.relationEndField;
            }
            set
            {
                this.relationEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationEndSpecified
        {
            get
            {
                return this.relationEndFieldSpecified;
            }
            set
            {
                this.relationEndFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum RelationTypeRelationEnd
    {

        /// <remarks/>
        Source,

        /// <remarks/>
        Target,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum DataTypeEnum
    {

        /// <remarks/>
        String,

        /// <remarks/>
        Integer,

        /// <remarks/>
        Decimal,

        /// <remarks/>
        Float,

        /// <remarks/>
        Boolean,

        /// <remarks/>
        DateTime,

        /// <remarks/>
        Time,

        /// <remarks/>
        Binary,

        /// <remarks/>
        EntityKey,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum SortDirectionEnum
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Ascending,

        /// <remarks/>
        Descending,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum AttributeTypeAlignment
    {

        /// <remarks/>
        General,

        /// <remarks/>
        Left,

        /// <remarks/>
        Center,

        /// <remarks/>
        Right,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum AttributeContextualNameEnum
    {

        /// <remarks/>
        Attribute,

        /// <remarks/>
        Role,

        /// <remarks/>
        Merge,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum AttributeTypeValueSelection
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Dropdown,

        /// <remarks/>
        List,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class ColumnType
    {

        private string tableNameField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TableName
        {
            get
            {
                return this.tableNameField;
            }
            set
            {
                this.tableNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class SortAttributeType
    {

        private AttributeReferenceType attributeReferenceField;

        private SortAttributeDirectionEnum sortDirectionField;

        private bool sortDirectionFieldSpecified;

        /// <remarks/>
        public AttributeReferenceType AttributeReference
        {
            get
            {
                return this.attributeReferenceField;
            }
            set
            {
                this.attributeReferenceField = value;
            }
        }

        /// <remarks/>
        public SortAttributeDirectionEnum SortDirection
        {
            get
            {
                return this.sortDirectionField;
            }
            set
            {
                this.sortDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortDirectionSpecified
        {
            get
            {
                return this.sortDirectionFieldSpecified;
            }
            set
            {
                this.sortDirectionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum SortAttributeDirectionEnum
    {

        /// <remarks/>
        Ascending,

        /// <remarks/>
        Descending,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public enum EntityTypeInstanceSelection
    {

        /// <remarks/>
        FilteredList,

        /// <remarks/>
        Dropdown,

        /// <remarks/>
        List,

        /// <remarks/>
        MandatoryFilter,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class EntityTypeInheritance
    {

        private System.Xml.XmlQualifiedName inheritsFromEntityIDField;

        private RelationType relationField;

        /// <remarks/>
        public System.Xml.XmlQualifiedName InheritsFromEntityID
        {
            get
            {
                return this.inheritsFromEntityIDField;
            }
            set
            {
                this.inheritsFromEntityIDField = value;
            }
        }

        /// <remarks/>
        public RelationType Relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling", IsNullable = false)]
    public partial class SemanticQuery
    {

        private HierarchyType[] hierarchiesField;

        private MeasureGroupType[] measureGroupsField;

        private ExpressionType[] calculatedAttributesField;

        private ParameterType[] parametersField;

        private bool enableDrillthroughField;

        private bool enableDrillthroughFieldSpecified;

        private CustomPropertyType[] customPropertiesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Hierarchy", IsNullable = false)]
        public HierarchyType[] Hierarchies
        {
            get
            {
                return this.hierarchiesField;
            }
            set
            {
                this.hierarchiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MeasureGroup", IsNullable = false)]
        public MeasureGroupType[] MeasureGroups
        {
            get
            {
                return this.measureGroupsField;
            }
            set
            {
                this.measureGroupsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Expression", IsNullable = false)]
        public ExpressionType[] CalculatedAttributes
        {
            get
            {
                return this.calculatedAttributesField;
            }
            set
            {
                this.calculatedAttributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable = false)]
        public ParameterType[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }

        /// <remarks/>
        public bool EnableDrillthrough
        {
            get
            {
                return this.enableDrillthroughField;
            }
            set
            {
                this.enableDrillthroughField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableDrillthroughSpecified
        {
            get
            {
                return this.enableDrillthroughFieldSpecified;
            }
            set
            {
                this.enableDrillthroughFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomProperty", IsNullable = false)]
        public CustomPropertyType[] CustomProperties
        {
            get
            {
                return this.customPropertiesField;
            }
            set
            {
                this.customPropertiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling", IsNullable = false)]
    public partial class DrillthroughContext
    {

        private string[] selectedItemsField;

        private RolePathItemType[] selectedPathField;

        private GroupingValuesTypeGroupingValue[] groupingValuesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SelectedItemName", IsNullable = false)]
        public string[] SelectedItems
        {
            get
            {
                return this.selectedItemsField;
            }
            set
            {
                this.selectedItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RolePathItem", IsNullable = false)]
        public RolePathItemType[] SelectedPath
        {
            get
            {
                return this.selectedPathField;
            }
            set
            {
                this.selectedPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("GroupingValue")]
        public GroupingValuesTypeGroupingValue[] GroupingValues
        {
            get
            {
                return this.groupingValuesField;
            }
            set
            {
                this.groupingValuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/2004/10/semanticmodeling")]
    public partial class GroupingValuesTypeGroupingValue
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

}
